spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true





#spring:
#  datasource:
#    url: jdbc:mysql://my-mysql:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ${DB_USER}
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
