#spring:
#  datasource:
#    url: jdbc:mysql://35.184.255.181:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: test
#    password: 1q2w3e4r
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
